name: Release gums3 (standalone)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v0.1.0)'
        required: true
      prerelease:
        description: 'Mark as prerelease'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  tag:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and push tag
        env:
          TAG: ${{ github.event.inputs.tag }}
        run: |
          set -euo pipefail
          if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists on origin. Nothing to do."
            exit 0
          fi
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git tag "$TAG"
          git push origin "$TAG"

  build-and-release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    env:
      DIST_DIR: dist
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build binaries
        run: |
          set -euo pipefail
          mkdir -p "$DIST_DIR"
          declare -a targets=(
            "linux amd64 gums3-linux_amd64"
            "darwin amd64 gums3-darwin_amd64"
            "darwin arm64 gums3-darwin_arm64"
            "windows amd64 gums3-windows_amd64.exe"
          )
          for t in "${targets[@]}"; do
            read -r GOOS GOARCH OUT <<< "$t"
            echo "Building $OUT"
            env CGO_ENABLED=0 GOOS="$GOOS" GOARCH="$GOARCH" go build -o "$DIST_DIR/$OUT" .
          done
          (cd "$DIST_DIR" && sha256sum * > SHA256SUMS.txt)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ github.event.inputs.prerelease || 'false' }}
          generate_release_notes: true
          files: |
            ${{ env.DIST_DIR }}/gums3-linux_amd64
            ${{ env.DIST_DIR }}/gums3-darwin_amd64
            ${{ env.DIST_DIR }}/gums3-darwin_arm64
            ${{ env.DIST_DIR }}/gums3-windows_amd64.exe
            ${{ env.DIST_DIR }}/SHA256SUMS.txt


